### ISSUE TITLE
Add responsive viewport meta tag to make website look better on smaller screens

### ISSUE THREAD

**Issue by jasenpau** [RD-github31/rd-github31.github.io#2]
In the `<head>` section adding a viewport meta tag would improve the layout of all the pages on small screens:

```html
<head>
  ...
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  ...
</head>
```

Source: [MDN Web docs - Viewport meta tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag)

**Comment by SomethingRD** [comment]
Thanks, I think I have fixed the website scaling now.
